# Build Stage for Backend
FROM maven:3.8.2-openjdk-17-slim AS backend-build
WORKDIR /app
COPY . .
RUN mvn clean install

# Runtime Stage
FROM openjdk:17-jdk-alpine AS runtime
WORKDIR /app
COPY --from=backend-build /app/pos-service/target/pos-service-1.0.0.jar app.jar
CMD ["java", "-jar", "app.jar"]
